[32m2023-12-17 08:09:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 59e6d95d-2c28-4560-bc8f-321cbbc31807 - 87430 - LOGS_CAPTURED - Started capturing logs in process (pid: 87430).
[32m2023-12-17 08:09:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 59e6d95d-2c28-4560-bc8f-321cbbc31807 - 87430 - parse_votes - STEP_START - Started execution of step "parse_votes".
[32m2023-12-17 08:09:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 59e6d95d-2c28-4560-bc8f-321cbbc31807 - 87430 - parse_votes - LOADED_INPUT - Loaded input "bulk_download" using input manager "local_io_manager"
[32m2023-12-17 08:09:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 59e6d95d-2c28-4560-bc8f-321cbbc31807 - 87430 - parse_votes - STEP_INPUT - Got input "bulk_download" of type "Any". (Type check passed).
[32m2023-12-17 08:14:46 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 59e6d95d-2c28-4560-bc8f-321cbbc31807 - 87430 - parse_votes - STEP_FAILURE - Execution of step "parse_votes" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "parse_votes"::

TypeError: list indices must be integers or slices, not str

Stack Trace:
  File "/Users/felix/Projects/codenym/DataPipelines/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/felix/Projects/codenym/DataPipelines/.venv/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 465, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/felix/Projects/codenym/DataPipelines/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/felix/Projects/codenym/DataPipelines/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/felix/Projects/codenym/DataPipelines/datanym/assets/HouseVotes/house_votes.py", line 79, in parse_votes
    data['bill_number'] = None
    ~~~~^^^^^^^^^^^^^^^

The above exception occurred during handling of the following exception:
TypeError: list indices must be integers or slices, not str

Stack Trace:
  File "/Users/felix/Projects/codenym/DataPipelines/datanym/assets/HouseVotes/house_votes.py", line 75, in parse_votes
    data['bill_number'] = data['bill']['number']
                          ~~~~^^^^^^^^
[0m
